name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:

  lint:
    name: "Lint"
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint

  floating:
    name: "Floating dependencies"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        try-scenario: 
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe
          - embroider-optimized
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
